language: go

go:
  - 1.6.2

sudo: required

env:
  global:
  - PGPORT=5432
  - PGHOST=localhost

services:
  - postgresql
  - docker

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5

before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - cat /etc/postgresql/9.5/main/pg_hba.conf
  - cat /etc/postgresql/9.5/main/postgresql.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'create database "khan";'
  - psql -U postgres khan -c 'create extension "uuid-ossp";'

install:
  - make setup-ci

script:
  - make coverage
  - make ci-perf

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile coverage-all.out -service=travis-ci
  - ./push_to_docker.sh
  - curl -H POST $TEST_FARM_URL
