language: go
go:
  - 1.6.2
  - tip
sudo: required
services:
  - postgresql
install:
  - make setup-ci
script:
  - make coverage
after_success:
  - goveralls -coverprofile=coverage-all.out -repotoken 1x4Z26mH24UgLN5V1INQQRppJtz7bG6RM
