language: go

go:
  - 1.6.2

sudo: required

env:
  global:
  - PGPORT=5432
  - PGHOST=localhost

services:
  - postgresql
  - docker

install:
  - sudo service postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y remove --purge postgresql-9.5
  - sudo apt-get -y autoremove
  - sudo rm -rf /etc/postgresql
  - sudo rm -rf /var/lib/postgresql
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get -y install postgresql-9.5
  - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo service postgresql restart
  - psql --version
  - psql -U postgres -d postgres -c "SHOW SERVER_VERSION"
  - psql -U postgres -c 'CREATE ROLE travis LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE;'
  - psql -U postgres -c 'CREATE ROLE khan_test LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE;'
  - psql -U postgres -c 'create database "khan";'
  - psql -U postgres khan -c 'create extension "uuid-ossp";'
  - make setup-ci

script:
  - make coverage
  - make ci-perf

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile coverage-all.out -service=travis-ci
  - ./push_to_docker.sh
  - /bin/bash -c '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ] && curl -H POST $TEST_FARM_URL'
