language: go

go:
  - 1.6.2

sudo: required

env:
  global:
  - PGPORT=5432
  - PGHOST=localhost

services:
  - postgresql
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y autoremove
  - psql --version
  - psql -U postgres -c 'CREATE ROLE khan_test LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE;'
  - psql -U postgres -c 'create database "khan";'
  - psql -U postgres khan -c 'create extension "uuid-ossp";'

install:
  - make setup-ci

script:
  - make coverage
  - make ci-perf

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile coverage-all.out -service=travis-ci
  - ./push_to_docker.sh
  - /bin/bash -c '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ] && curl -H POST $TEST_FARM_URL'
