language: go

go:
  - 1.6.2

sudo: required

services:
  - postgresql
  - docker

addons:
  postgresql: "9.4"

install:
  - make setup-ci

script:
  - make coverage
  - $HOME/gopath/bin/goveralls -coverprofile coverage-all.out -service=travis-ci

after_success:
  - ./push_to_docker.sh
  - curl -H POST $TEST_FARM_URL
