language: go

go:
  - 1.6.2

sudo: required

services:
  - postgresql
  - docker

install:
  - make setup-ci
  - make drop-test

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

deploy:
  - ./push_to_docker.sh
