[[constraint]]
  name = "github.com/labstack/echo"
  version = "2.0.2"

[[constraint]]
  name = "github.com/newrelic/go-agent"
  version = "1.1.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.2.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/topfreegames/goose"

[[constraint]]
  name = "github.com/topfreegames/extensions"
  version = "8.0.5"

[[constraint]]
  name = "github.com/go-gorp/gorp"
  version = "2.1"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v5"
  version = "5.0.39"

[[constraint]]
  name = "github.com/mailru/easyjson"
  branch = "master"

[[override]]
  name = "github.com/spf13/viper"
  revision = "25b30aa063fc18e48662b86996252eabdcf2f0c7"

[prune]
  go-tests = true
  unused-packages = true
