postgres:
  user: "postgres"
  dbName: "khan"
  host: "localhost"
  port: 5433
  sslMode: "disable"

elasticsearch:
  enabled: true
  host: "localhost"
  port: 9200
  sniff: false
  index: "khan"

khan:
  maxPendingInvites: -1
  defaultCooldownBeforeInvite: 0
  defaultCooldownBeforeApply: 3600

healthcheck:
  workingText: "WORKING"

webhooks:
  timeout: 2

sentry:
  url: ""

newrelic:
  key: ""
