postgres:
  user: "khan"
  dbName: "khan"
  host: "localhost"
  port: 5433
  sslMode: "disable"

elasticsearch:
  enabled: true
  host: "localhost"
  port: 9200
  sniff: false
  index: "khan"

webhooks:
  timeout: 2
  workers: 50
  bufferSize: 50000

healthcheck:
  workingText: "WORKING"

newrelic:
  key: ""
