postgres:
  user: "khan"
  dbName: "khan"
  host: "localhost"
  port: 5433
  sslMode: "disable"

elasticsearch:
  enabled: true
  host: "localhost"
  port: 9200
  sniff: false
  index: "khan"

mongodb:
  enabled: false
  url: mongodb://localhost:27017
  databaseName: "khan"
  collectionTemplate: "clans_%s"

webhooks:
  timeout: 2
  workers: 5
  statsPort: 9999
  runStats: true

healthcheck:
  workingText: "WORKING"

newrelic:
  key: ""

redis:
  host: 0.0.0.0
  port: 50505
  database: 0
  pool: 30
  password: ""
