postgres:
  user: "postgres"
  dbName: "khan"
  host: "localhost"
  port: 5555
  sslMode: "disable"
elasticsearch:
  enabled: true
  host: "localhost"
  port: 9234
  sniff: false
  index: "khan"
healthcheck:
  workingText: "WORKING"
