postgres:
  user: "khan_test"
  dbName: "khan_test"
  host: "localhost"
  port: 5432
  sslMode: "disable"
elasticsearch:
  host: "localhost"
  enabled: true
  port: 9200
  sniff: false
  index: "khan"
khan:
  maxPendingInvites: -1
  defaultCooldownBeforeInvite: 0
  defaultCooldownBeforeApply: 3600

healthcheck:
  workingText: "WORKING"

webhooks:
  timeout: 2
