version: '2'

services:
  postgres:
    image: postgres:9.5
    ports:
      - "5433:5432"
  elasticsearch:
    image: elasticsearch:2.4
    command: "elasticsearch -Des.node.name=khan-master"
    ports:
      - "9200:9200"
  redis:
    image: redis
    ports:
      - "50505:6379"
